name: landmarks
description: A Flutter implementation of the SwiftUI main tutorial
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  apple_maps_flutter: ^1.2.0
  cupertino_icons: ^1.0.5
  intl: ^0.18.0

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1

flutter:
  assets:
   - assets/

flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: assets/landmark_app_icon_1024x1024.png